---
title: "Emenda Parlamentar (total aplicado entre 2015 a agosto de 2022)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
options(encoding = 'Latin1',digits = 3,scipen=999 )
```


```{r}
library(tidyverse)
library(DT)
library(janitor)
library(readxl)
library(ggplot2)
library(plotly)
library(leaflet)
library(openxlsx)
library(shiny)
library(shinyWidgets)
library(pre)
```

```{r}
tabela_reais = function (df,coluna = NULL) {
      datatable((df)%>%
  # "row" para o total aparecer na linha, ou seja, totalizar os valores de uma coluna
  adorn_totals("row") ,
      filter = 'top', 
      rownames = FALSE,
      extensions = 'Buttons',
      options = list( 
                  # order = list (df[(length(df))], 'desc'),
                  dom = "Blfrtip",
                  buttons = 
                    list("copy", list(
                      extend = "collection",
                      buttons = c("csv", "excel", "pdf"),
                      text = "Download" ) ),
                  lengthMenu = list( c(-1, 10, 15,20),
                                     c( "tudo",10, 15, 20)),
                  pageLength =15 )
      )%>%
  formatRound(
  # formatar apenas as colunas numericas.
  # sapply para identificar as colunas numericas e combinar com o parametro COLUNA
    # ((ncol(df %>% select_if(is.character))+1):(ncol(df )+1)),
    # http://datamining.togaware.com/survivor/Remove_Non_Numeric.html
    (c(colnames(df[,sapply(df, is.numeric)]), coluna)),
  digits = 2,
  interval = 3,
  mark = ".",
  dec.mark = ","
) 
}
```

```{r}
emendas <- read_excel("emendas_hist.xlsx",     skip = 8)




emendas <-    clean_names(emendas)

emendas <-  rename(emendas, despesas_pagas =movim_liquido_r_item_informacao )

emendas <- emendas %>% filter(!is.na(despesas_pagas), )

emendas <- emendas %>% filter(autor_emendas_orcamento_nome != "PTRES ANTERIOR A 2015")

emendas <- emendas %>% separate(autor_emendas_orcamento_nome, into = c("autor_emenda","numero_emenda"), sep = "/" )

emendas <- emendas %>% mutate (autor_emenda = str_trim(autor_emenda))


emendas <- emendas %>% mutate(mun_uf = str_c (municipio_cel, "-",uf_cel_sigla))





library(readr)
TABMUN <- read_delim("TABMUN.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE) 

TABMUN <- TABMUN %>% mutate(mun_uf = str_c (municipio_cel, "-",uf_cel_sigla))

# adicionar o código IBGE à DF emendas
emendas <- left_join(emendas,TABMUN %>% select(municipio_cel, codigo_ibge))

# municipios <- read_csv("https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv")

municipios <- read_excel("municipios.xlsx")

municipios <-  rename(municipios,   nome_mun =nome ) %>% select(!codigo_uf)


emendas <- left_join(emendas, municipios) 

emendas <- emendas %>% mutate(nome_mun_uf = str_c(nome_mun,"-",uf_cel_sigla))

# write.xlsx(municipios,"municipios.xlsx")
# 
# 
# estados <- read_csv("https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/estados.csv")
# 
# estados <- rename(estados, latitude_uf = latitude)
# estados <- rename(estados,   longitude_uf =longitude )
# estados <-  rename(estados,   nome_uf =nome )
```



```{r}
emendas <-  emendas %>% mutate (code_regiao = case_when(
  
  regiao_cel == "NORTE" ~ 1,
  regiao_cel == "NORDESTE" ~ 2,
  regiao_cel == "SUDESTE" ~ 3,
  regiao_cel == "SUL" ~ 4,
  regiao_cel == "CENTRO-OESTE" ~ 5
  ))


emendas <- emendas %>% mutate(tipo_local =   case_when(
  municipio_cel != "SEM INFORMACAO" ~ "município",
  regiao_cel == "CENTRO-OESTE" & uf_cel_nome == "SEM INFORMACAO" ~ "regiao",
  regiao_cel == "NORTE"& uf_cel_nome == "SEM INFORMACAO" ~ "regiao",
  regiao_cel == "SUL" & uf_cel_nome == "SEM INFORMACAO"~ "regiao",
  regiao_cel == "NORDESTE"& uf_cel_nome == "SEM INFORMACAO" ~ "regiao",
  regiao_cel == "SUDESTE" & uf_cel_nome == "SEM INFORMACAO"~ "regiao",
  regiao_cel == "EXTERIOR" & uf_cel_nome == "SEM INFORMACAO"~ "Exterior",
  regiao_cel == "NACIONAL" & uf_cel_nome == "SEM INFORMACAO"~ "Brasil",
  TRUE ~ "UF"
  
  ))


# emendas <- emendas %>%  mutate (local = case_when(
#   tipo_local == "município"  ~ mun_uf,
#   tipo_local == "UF"  ~ str_c ( uf_cel_sigla,": municípios não identificados"),
#   tipo_local == "Região"  ~ str_c ( regiao_cel,": municípios não identificados"),
#   tipo_local == "Brasil"  ~ str_c ( tipo_local,": municípios não identificados"),
#   tipo_local == "Exterior"  ~ str_c ( tipo_local),
#   
# ))


emendas <- emendas %>%  mutate (local = case_when(

  tipo_local == "UF"  ~ uf_cel_sigla,
  tipo_local == "regiao"  ~ regiao_cel,
  tipo_local == "Brasil"  ~ tipo_local,
  tipo_local == "Exterior"  ~ tipo_local,
    tipo_local == "município" ~ nome_mun_uf
))

emendas <- emendas %>% mutate(sigla = case_when(
  
  local == "CENTRO-OESTE" ~ "CO",
  local == "NORDESTE" ~ "NE",
  local == "SUL" ~ "S",
  local == "NORTE" ~ "N",
  local == "SUDESTE" ~ "SE"))
```




```{r message=FALSE, include=FALSE}
library(geobr)

#| collapse: true

regiao <- read_region(year=2020) 
regiao <- regiao %>% mutate(sigla = case_when(
  
  name_region == "Centro Oeste" ~ "CO",
  name_region == "Nordeste" ~ "NE",
  name_region == "Sul" ~ "S",
  name_region == "Norte" ~ "N",
  name_region == "Sudeste" ~ "SE"))



uf <- read_state(year = 2020)


# cidades <- read_municipal_seat(year = 2010)

```
```{r}
emendas_react <- reactive(emendas %>% filter(autor_emenda %in% input$autor))

filtro_uf <- reactive (emendas_react() %>% filter(tipo_local == "UF"))

filtro_regiao <- reactive (emendas_react() %>% filter(tipo_local == "regiao"))

# geo_municipio <-reactive(left_join(emendas_react() %>% filter(tipo_local== "município") %>% select(codigo_ibge, autor_emenda, despesas_pagas), municipios))

geo_municipio <-reactive(emendas_react() %>% filter(tipo_local== "município") )



geo_uf <- reactive( uf %>%  filter (abbrev_state %in% unique(filtro_uf()$uf_cel_sigla)))


geo_regiao <- reactive( regiao %>%  filter (sigla %in% unique(filtro_regiao()$sigla)))
# geo_regiao <- (left_join (emendas %>% filter(tipo_local== "regiao") %>% select(local, autor_emenda), regiao, by = c("local"= "name_region")))
# 
# addPolygons(data = regiao %>% filter(code_region %in% unique(autor() %>% filter(tipo_local== "Região") %>% select(code_regiao))))  %>%
#   addPolygons(data = uf %>% filter (abbrev_state %in% unique(autor() %>% filter(tipo_local== "UF") %>% select(uf_cel_sigla))), fillColor = topo.colors(100, alpha = NULL), stroke = FALSE) %>% 
#    addMarkers(data = cidades %>% filter(code_muni %in% autor()$codigo_ibge),  clusterOptions = markerClusterOptions())

```



```{r eval=FALSE, include=FALSE}
p <- emendas %>% group_by(orgao_uge_nome) %>% summarise(despesas_pagas = sum(despesas_pagas)) %>%
  ggplot(aes(x = (fct_reorder(orgao_uge_nome, despesas_pagas)), y = despesas_pagas, fill = orgao_uge_nome)) +
  geom_col() + 
  labs(x = "autor")+ coord_flip()+
   scale_fill_discrete()+
  theme(legend.position = "none")  
ggplotly(p)
```



```{r eval=FALSE, include=FALSE}
p <- emendas %>% group_by(regiao_cel) %>% summarise(despesas_pagas = sum(despesas_pagas)) %>%
  ggplot(aes(x = (fct_reorder(regiao_cel, despesas_pagas)), y = despesas_pagas, fill = regiao_cel)) +
  geom_col() + 
  labs(x = "autor")+ coord_flip()+
   scale_fill_discrete()+
  theme(legend.position = "none")  
ggplotly(p)

```


```{r eval=FALSE, include=FALSE}
p <- emendas %>% group_by(ano_lancamento, orgao_uge_nome) %>% summarise(despesas_pagas = sum(despesas_pagas)) %>%
  ggplot(aes(x = ano_lancamento, y = despesas_pagas, fill = orgao_uge_nome)) +
  geom_col() + 
  labs(x = "ano")+ 
   scale_fill_discrete()+
  theme(legend.position = "none")  
ggplotly(p)
```

```{r eval=FALSE, include=FALSE}
p <- emendas %>% group_by(ano_lancamento, resultado_eof_codigo) %>% summarise(despesas_pagas = sum(despesas_pagas)) %>%
  ggplot(aes(x = ano_lancamento, y = despesas_pagas, fill = resultado_eof_codigo)) +
  geom_col() + 
  labs(x = "ano")+ 
   scale_fill_discrete()+
  theme(legend.position = "none")  
ggplotly(p)
```

Inputs {.sidebar}
-------------------------------------
```{r}


selectInput  ("autor", label = h3("Escolha o autor da emenda"), 
    choices = sort(unique(emendas$autor_emenda), decreasing = FALSE), 
   
    selected = "EDUARDO BOLSONARO", selectize = TRUE,multiple = TRUE)


```




Column {data-width=450}
-----------------------------------------------------------------------


### Mapa

```{r}



renderLeaflet({
  
   leaflet() %>% addTiles() %>%
  addPolygons(data = geo_regiao())  %>%
  addPolygons(data = geo_uf()) %>%
    addMarkers(data = geo_municipio(),  clusterOptions = markerClusterOptions()  , label = str_c(geo_municipio()$nome_mun,": " ,prettyNum( geo_municipio()$despesas_pagas, big.mark = ".", decimal.mark = "," )))
  
})

```

Column {.tabset}
-----------------------------------------------------------------------


### Por localidade


```{r}


renderDT({tabela_reais(emendas_react() %>% group_by(  local, tipo_local) %>% summarise(valor_pago = sum(despesas_pagas)))}) 
```


### Tabela

```{r}


renderDT({tabela_reais(emendas_react() %>% group_by( autor_emenda, local, tipo_local, orgao_uge_nome,acao_governo_nome, programa_governo_nome) %>% summarise(valor_pago = sum(despesas_pagas)))}) 
```

